update yml

diff --git a/.github/workflows/terraform-ci.yml b/.github/workflows/terraform-ci.yml
--- a/.github/workflows/terraform-ci.yml
+++ b/.github/workflows/terraform-ci.yml
@@ -22,8 +22,20 @@ jobs:
       with:
         terraform_version: '1.9.7' 
 
-    - name: Terraform Format
-      run: terraform fmt -recursive -check
+    - name: Terraform Format Check
+      run: |
+        set -e  # Exit immediately if any command fails
+        terraform fmt -recursive -check
+        if [ $? -ne 0 ]; then
+          echo "Terraform format check failed"
+          exit 1  # Explicitly set the failure status
+        fi
 
     - name: Terraform Validate
-      run: terraform validate
+      run: |
+        set -e  # Exit immediately if any command fails
+        terraform validate
+        if [ $? -ne 0 ]; then
+          echo "Terraform validation failed"
+          exit 1  # Explicitly set the failure status
+        fi
